<a href="https://colab.research.google.com/github/SLVmain/PyTorch_start/blob/Les_01/HW_01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.FloatTensor(3, 4, 5)

In [ ]:
x

tensor([[[8.4717e-16, 3.0864e-41, 2.8727e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.9422e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20],
         [2.3078e-12, 1.8788e+31, 7.9303e+34, 6.1949e-04, 1.8038e+28]],

        [[4.2324e+21, 7.1536e+22, 1.8180e+31, 1.4580e-19, 1.1495e+24],
         [3.0956e-18, 9.4370e-09, 1.0733e-08, 6.5712e-07, 1.6503e-07],
         [1.3149e+22, 3.3609e+21, 1.0533e+21, 2.1029e+20, 2.4693e-18],
         [8.2207e+32, 1.8394e+25, 6.1963e-04, 4.1185e-11, 1.4580e-19]],

        [[1.8179e+31, 1.8524e+28, 2.1715e-18, 8.5382e-07, 6.6466e+22],
         [1.3458e+22, 5.4071e+22, 1.3400e-08, 2.1235e+20, 1.6804e-04],
         [2.1865e+23, 2.1707e-18, 7.2128e+22, 2.1715e-18, 1.0372e-08],
         [1.0072e-11, 1.2352e-08, 2.5644e-09, 4.2109e-11, 4.1488e-08]]])

In [ ]:
x.size()

torch.Size([3, 4, 5])

In [ ]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [ ]:
# Приведите его к форме 6 X 10
x.reshape(6, 10)

tensor([[8.4717e-16, 3.0864e-41, 2.8727e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.9422e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20, 2.3078e-12,
         1.8788e+31, 7.9303e+34, 6.1949e-04, 1.8038e+28],
        [4.2324e+21, 7.1536e+22, 1.8180e+31, 1.4580e-19, 1.1495e+24, 3.0956e-18,
         9.4370e-09, 1.0733e-08, 6.5712e-07, 1.6503e-07],
        [1.3149e+22, 3.3609e+21, 1.0533e+21, 2.1029e+20, 2.4693e-18, 8.2207e+32,
         1.8394e+25, 6.1963e-04, 4.1185e-11, 1.4580e-19],
        [1.8179e+31, 1.8524e+28, 2.1715e-18, 8.5382e-07, 6.6466e+22, 1.3458e+22,
         5.4071e+22, 1.3400e-08, 2.1235e+20, 1.6804e-04],
        [2.1865e+23, 2.1707e-18, 7.2128e+22, 2.1715e-18, 1.0372e-08, 1.0072e-11,
         1.2352e-08, 2.5644e-09, 4.2109e-11, 4.1488e-08]])

In [ ]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
y = torch.tensor([1, 4, 2, 2, 1])
print(x)
print(y)
mult_xy = x * y
mult_xy

tensor([[[8.4717e-16, 3.0864e-41, 2.8727e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.9422e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20],
         [2.3078e-12, 1.8788e+31, 7.9303e+34, 6.1949e-04, 1.8038e+28]],

        [[4.2324e+21, 7.1536e+22, 1.8180e+31, 1.4580e-19, 1.1495e+24],
         [3.0956e-18, 9.4370e-09, 1.0733e-08, 6.5712e-07, 1.6503e-07],
         [1.3149e+22, 3.3609e+21, 1.0533e+21, 2.1029e+20, 2.4693e-18],
         [8.2207e+32, 1.8394e+25, 6.1963e-04, 4.1185e-11, 1.4580e-19]],

        [[1.8179e+31, 1.8524e+28, 2.1715e-18, 8.5382e-07, 6.6466e+22],
         [1.3458e+22, 5.4071e+22, 1.3400e-08, 2.1235e+20, 1.6804e-04],
         [2.1865e+23, 2.1707e-18, 7.2128e+22, 2.1715e-18, 1.0372e-08],
         [1.0072e-11, 1.2352e-08, 2.5644e-09, 4.2109e-11, 4.1488e-08]]])
tensor([1, 4, 2, 2, 1])


tensor([[[8.4717e-16, 1.2345e-40, 5.7453e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.9422e+31, 1.0996e+21, 1.2390e-03, 3.8843e+31, 2.7491e+20],
         [2.3078e-12, 7.5151e+31, 1.5861e+35, 1.2390e-03, 1.8038e+28]],

        [[4.2324e+21, 2.8614e+23, 3.6359e+31, 2.9161e-19, 1.1495e+24],
         [3.0956e-18, 3.7748e-08, 2.1465e-08, 1.3142e-06, 1.6503e-07],
         [1.3149e+22, 1.3443e+22, 2.1065e+21, 4.2058e+20, 2.4693e-18],
         [8.2207e+32, 7.3577e+25, 1.2393e-03, 8.2370e-11, 1.4580e-19]],

        [[1.8179e+31, 7.4094e+28, 4.3430e-18, 1.7076e-06, 6.6466e+22],
         [1.3458e+22, 2.1628e+23, 2.6801e-08, 4.2471e+20, 1.6804e-04],
         [2.1865e+23, 8.6830e-18, 1.4426e+23, 4.3430e-18, 1.0372e-08],
         [1.0072e-11, 4.9408e-08, 5.1289e-09, 8.4217e-11, 4.1488e-08]]])

In [ ]:
x.shape

torch.Size([3, 4, 5])

In [ ]:
x = x.view(6,10)

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(x, x.T)

tensor([[7.1769e-31, 1.6453e+16, 3.5856e+06, 1.1139e+07, 1.5401e+16, 1.8523e+08],
        [1.6453e+16,        inf,        inf,        inf,        inf,        inf],
        [3.5856e+06,        inf,        inf,        inf,        inf,        inf],
        [1.1139e+07,        inf,        inf,        inf,        inf,        inf],
        [1.5401e+16,        inf,        inf,        inf,        inf,        inf],
        [1.8523e+08,        inf,        inf,        inf,        inf,        inf]])

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

z = y = x**3 + z - 75*t


x = Variable(torch.FloatTensor([1]),   requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward([x, z, t])

(x.grad, z.grad, t.grad)

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

In [ ]:
# Создаем тензоры
x = torch.tensor(1.)
z = torch.tensor(0.5)
t = torch.tensor(2.)
x = Variable(x, requires_grad=True)
z = Variable(z, requires_grad=True)
t = Variable(t, requires_grad=True)

In [ ]:
# Строим вычислительный граф
y = x**3 + z - 75*t
y

tensor(-148.5000, grad_fn=<SubBackward0>)

In [ ]:
x**3 + z - 75*t

tensor(-148.5000, grad_fn=<SubBackward0>)

In [ ]:
# Вычисляем градиенты (выполняем обратный проход и получаем производную всех переменных)
y.backward()

In [ ]:
# Посмотрим градиенты для каждого из задействованных тензоров
print(x.grad)    
print(z.grad)    
print(t.grad)    

tensor(3.)
tensor(1.)
tensor(-75.)


In [ ]:
x.grad + z.grad + t.grad

tensor(-71.)

In [ ]:
# Создайте единичный тензор размера 5x6
a = torch.ones(5,6)
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Переведите его в формат numpy
c = a.numpy() 
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [24]:
from torch.autograd import Variable

dtype = torch.float
device = torch.device("cpu")

x = torch.randn(1) # матрица случайных значений, соответствующих нормальному распределению 
y = torch.randn(1)
x = Variable(x) #requires_grad=False по умолчанию
y = Variable(y) #requires_grad=False по умолчанию

w1 = torch.full((), 0.0, device=device, dtype=dtype, requires_grad=True)

In [25]:
print(x)
print(y)
print(w1)

tensor([0.8971])
tensor([-0.3086])
tensor(0., requires_grad=True)


In [26]:
optimizer = torch.optim.SGD([w1], lr=0.01)

In [27]:
criterion = torch.nn.MSELoss()

In [28]:
y_pred = x**w1 - 2 * x**2 + 5

In [29]:
optimizer.zero_grad()

In [30]:
loss = criterion(y_pred, y)

In [31]:
loss.backward()     

In [32]:
optimizer.step()   

In [23]:
#loss.item()

In [33]:
print(loss.detach())
print({w1.data})

tensor(22.0814)
{tensor(0.0102)}


In [34]:
# сделаем несколько эпох
for i in range(100): 
    
    y_pred = x**w1 - 2 * x**2 + 5

    # Считаем функцию ошибки
    loss = criterion(y_pred, y)

    # Обнуляем вручную градиент на каждой итерации
    optimizer.zero_grad()

    # Обратное распространение ошибки
    loss.backward()

    # Делаем шаг градиентного спуска
    optimizer.step()
    
    if i%10 ==0:
        print(loss.detach())

tensor(22.0710)
tensor(21.9684)
tensor(21.8685)
tensor(21.7712)
tensor(21.6763)
tensor(21.5838)
tensor(21.4936)
tensor(21.4056)
tensor(21.3197)
tensor(21.2358)


In [ ]:
# из документации по torch скопироваля памятку

# Create random Tensors for weights. For this example, we need
# 1 weight: y = x**w1 - 2 * x**2 + 5, 
# these weights need to be initialized
# not too far from the correct result to ensure convergence.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.full((), 0.0, device=device, dtype=dtype, requires_grad=True)


learning_rate = 5e-6
for t in range(11):
    

    # Forward pass: compute predicted y using operations; we compute
    # P3 using our custom autograd operation.
    y_pred = x**w1 - 2 * x**2 + 5

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum()
    if t % 5 == 4:
        print(t, loss.item())

    # Use autograd to compute the backward pass.
    loss.backward()

    # Update weights using gradient descent
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        

        # Manually zero the gradients after updating weights
        w1.grad = None
        

print(f'Result: y = {w1.item()} x -2 *x**2 +5')
